### ISSUE TITLE
Extra "E-X-T-R-A" awards

### ISSUE THREAD

**Issue by BusterBrawls** [MiSTer-devel/Arcade-MrDo_MiSTer#1]
I collected the EXTRA bonus and received an extra Mr Do, as expected. Not all of the EXTRA tokens gets cleared though and I am left with 3 of the EXTRA tokens already collected when the next level begins.

**Comment by va7deo** [comment]
I am able to reproduce this.

**Comment by BusterBrawls** [comment]
Fixed by updated mra
