### ISSUE TITLE
Difficulty doesn't increase and bonus prizes don't change

### ISSUE THREAD

**Issue by Kewydee** [MiSTer-devel/Arcade-MrDo_MiSTer#10]
I've noticed that the monsters don't get any more aggressive at all. They stay at scene 1 speed and do not speed up. Also from scene 3 onwards there should be 8 monsters spawned from the centre. Currently only 6 monsters spawn.

The bonuses for the centre prizes should follow this order - From Stratagywiki - https://strategywiki.org/wiki/Mr._Do!/How_to_play

**Comment by va7deo** [comment]
I believe this is related to #9.  Protection hack didn't work so implemented the PAL IC.
