### ISSUE TITLE
Mr. Do - Cake only appears for Bonus Food

### ISSUE THREAD

**Issue by lanceyd1027** [MiSTer-devel/Arcade-MrDo_MiSTer#9]
Hi! BIg Mr. Do fan and new to MiSter. So was checking out the Mr. Do core and noticed that the in-game Bonus Food Item wasn't changing from a Cake to the others. I also played with some of the Dip Switches (Modes, etc), but nothing fixed it.

Anyone else see this and or fixed it? The Cake bonus is only a 1000 points and the others gradually get larger. Here is an excerpt I found on the the net:

_Bonus food items come up on every level of Mr. Do! Starting on the first level, next food bonuses are revealed every one to two boards, all the way until the 22nd stage. Food items include milk cartons, sandwiches, pancakes, burgers, candy bars and ice cream sundaes. These bonuses will range from 1,000 to 8,000 points, so it will be adventitious for you to collect them whenever possible._

**Comment by va7deo** [comment]
Bonus food now changes on each level.  Protection hack didn't work so implemented the PAL IC based on dumped jed file.
